Fixed check script; added --check flag to build script; added argument parsing to check and build script; added documentation to NoneTextDisplay; renamed multiboot2 section to bootheader

diff --git a/kernel/build b/kernel/build
--- a/kernel/build
+++ b/kernel/build
@@ -1,7 +1,50 @@
 #!/bin/bash
 
 (
-    set -e
+    set -o errexit -o pipefail -o noclobber
+
+    HAVE_GETOPT=true
+    getopt --test > /dev/null && true
+    if [[ $? -ne 4 ]]; then
+        if [[ -n "EXIT_WITHOUT_GETOPT" ]]; then
+            echo '`getopt --test` failed. Exiting.'
+            exit 1
+        else
+            echo '`getopt --test` failed. Continuing and ignoring command line flags. (note that $1 will still be used for the target)'
+            echo '(to exit instead of ignoring, set the environment variable `EXIT_WITHOUT_GETOPT` to a non-null value)'
+            HAVE_GETOPT=false
+        fi
+    fi
+
+    check=false
+
+    if [[ "$HAVE_GETOPT" = "true" ]]; then
+        LONGOPTS=check
+        OPTIONS=c
+
+        PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTS --name "$0" -- "$@") || (
+            echo '`getopt` failed to parse command line arguments. Check the arguments passed.'
+            exit 1
+        )
+        eval set -- "$PARSED"
+
+        while true; do
+            case "$1" in
+                -c|--check)
+                    check=true
+                    shift
+                    ;;
+                --)
+                    shift
+                    break
+                    ;;
+                *)
+                    echo "Unknown argument"
+                    exit 1
+                    ;;
+            esac
+        done
+    fi
 
     export KERNEL_DIR=$(readlink -e .)
 
@@ -38,20 +81,24 @@
         real_target=${!target}
         real_target=$(basename $real_target)
         echo "Compiling target $target(with rust target of $real_target)"
-        cargo build --target "$real_target" --release -Zbuild-std=core,alloc --bin entrypoint_$target
-        cp "target/$(echo $real_target | sed 's/\.json//')/release/entrypoint_$target" kernel-$target
+        if [[ $check = "true" ]]; then
+            cargo check --target "$real_target" --release -Zbuild-std=core,alloc --bin entrypoint_$target
+        else
+            cargo build --target "$real_target" --release -Zbuild-std=core,alloc --bin entrypoint_$target
+            cp "target/$(echo $real_target | sed 's/\.json//')/release/entrypoint_$target" kernel-$target
 
-        if [[ "$CONFIG_BUILD_GRUB" = "true" ]]; then
-            if [[ "$target" = "x86" || "$target" = "mips64" || "$target" = "mipsel" || "$target" = "mipsle" ]]; then
-                rm -rf grub aphrodite-grub-$target.iso
-                cp -r ./grub_template ./grub
+            if [[ "$CONFIG_BUILD_GRUB" = "true" ]]; then
+                if [[ "$target" = "x86" || "$target" = "mips64" || "$target" = "mipsel" || "$target" = "mipsle" ]]; then
+                    rm -rf grub aphrodite-grub-$target.iso
+                    cp -r ./grub_template ./grub
 
-                cp kernel-$target ./grub/boot/aphrodite.kernel
+                    cp kernel-$target ./grub/boot/aphrodite.kernel
 
-                sed -i "s@%{VERSION}@$VERSION@g" ./grub/boot/grub/grub.cfg
+                    sed -i "s@%{VERSION}@$VERSION@g" ./grub/boot/grub/grub.cfg
 
-                grub-mkrescue -o aphrodite-grub-$target.iso grub
-                cp aphrodite-grub-$target.iso aphrodite-$target.iso
+                    grub-mkrescue -o aphrodite-grub-$target.iso grub
+                    cp aphrodite-grub-$target.iso aphrodite-$target.iso
+                fi
             fi
         fi
     }
diff --git a/kernel/check b/kernel/check
--- a/kernel/check
+++ b/kernel/check
@@ -1,14 +1,88 @@
 #!/bin/bash
 
-# Build the file
-./build
+(
+    set -o errexit -o pipefail -o noclobber
 
-if grub-file --is-x86-multiboot2 kernel.flat; then
-    echo "Multiboot2 header valid" > ./check_results
-else
-    echo "Multiboot2 header INVALID!" > ./check_results
-fi
+    HAVE_GETOPT=true
+    getopt --test > /dev/null && true
+    if [[ $? -ne 4 ]]; then
+        if [[ -n "EXIT_WITHOUT_GETOPT" ]]; then
+            echo '`getopt --test` failed. Exiting.'
+            exit 1
+        else
+            echo '`getopt --test` failed. Continuing and ignoring command line flags. (note that $1 will still be used for the target)'
+            echo '(to exit instead of ignoring, set the environment variable `EXIT_WITHOUT_GETOPT` to a non-null value)'
+            HAVE_GETOPT=false
+        fi
+    fi
 
-echo
+    real_check=false
 
-cat check_results
+    if [[ "$HAVE_GETOPT" = "true" ]]; then
+        LONGOPTS=real_check
+        OPTIONS=c
+
+        PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTS --name "$0" -- "$@") || (
+            echo '`getopt` failed to parse command line arguments. Check the arguments passed.'
+            exit 1
+        )
+        eval set -- "$PARSED"
+
+        while true; do
+            case "$1" in
+                -c|--real_check)
+                    real_check=true
+                    shift
+                    ;;
+                --)
+                    shift
+                    break
+                    ;;
+                *)
+                    echo "Unknown argument"
+                    exit 1
+                    ;;
+            esac
+        done
+    fi
+
+    if [[ $real_check = "true" ]]; then
+        ./build --check $!
+    else
+        ./build $!
+    fi
+
+    rm ./check_results
+
+    target="$1"
+
+    if [[ -z "$target" || "$target" = "x86" || "$target" = "mips64" || "$target" = "mipsel" || "$target" = "mipsle" ]]; then
+        if [[ -z "$target" ]]; then
+            # -f makes it so it won't error out if the file doesn't exist
+            rm -f targets.tmp
+            envsubst < "targets" > "targets.tmp"
+
+            export $(grep -Ev '^#' targets.tmp | xargs)
+            
+            for target in $TARGETS; do
+                if grub-file --is-x86-multiboot2 kernel-$target; then
+                    echo "Multiboot2 header valid" > ./check_results
+                else
+                    echo "Multiboot2 header INVALID!" > ./check_results
+                fi
+            done
+        else
+            if grub-file --is-x86-multiboot2 kernel-$target; then
+                echo "Multiboot2 header valid" > ./check_results
+            else
+                echo "Multiboot2 header INVALID!" > ./check_results
+            fi
+        fi
+    else
+        echo "Multiboot2 header not checked as neither x86 nor mips is being built" > ./check_results
+    fi
+
+    echo
+
+    cat check_results
+)
